# Generated by Django 5.0.3 on 2024-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_room_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='num_of_replies',
            field=models.IntegerField(default=0),
        ),
    ]
