# Generated by Django 5.0.3 on 2024-06-03 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_num_of_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replymessage',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AddField(
            model_name='message',
            name='liker',
            field=models.ManyToManyField(blank=True, related_name='message_liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
