# Generated by Django 5.0.3 on 2024-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(null=True, upload_to='images/room_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar.svg', null=True, upload_to='images/profile_images'),
        ),
    ]
