# Generated by Django 5.0.3 on 2024-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_roomimage_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(default='images/room_images/default_room_image.png', upload_to='images/room_images'),
        ),
    ]
