# Generated by Django 5.0.3 on 2024-06-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_roomimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomImage',
            field=models.ImageField(default='images/room_images/default_room_image.png', null=True, upload_to='images/room_images'),
        ),
    ]
