# Generated by Django 5.0.3 on 2024-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(null=True, upload_to='file/audio_messages'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='file/video_messages'),
        ),
    ]
