# Generated by Django 5.0.3 on 2024-06-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_message_audio_message_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(null=True, upload_to='files/audio_messages'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='files/video_messages'),
        ),
    ]
