# Generated by Django 5.0.3 on 2024-06-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_replymessage_audio_replymessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(null=True, upload_to='files/messages/audio_messages'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(null=True, upload_to='files/messages/image_messages'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(null=True, upload_to='files/messages/video_messages'),
        ),
    ]
